### PR TITLE
added a check to see whether dir exists

### PR DESCRIPTION
**Pull request by ameet123**
on windows /tmp does not exist, as such I was getting an error, added this to create this directory

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ameet123 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=Pivotal-Field-Engineering/ephemerol&pullRequestId=9)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=Pivotal-Field-Engineering/ephemerol&pullRequestId=9) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ameet123 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=Pivotal-Field-Engineering/ephemerol&pullRequestId=9)!

**Comment by ameet123** [comment]
Yes, that would work, since tempfile.tempdir does indeed search through standard names/ env variables and one of them is 'TMP', which does indeed have a value on windows - generally Local\Temp.
so that would be a better way I think.
thanks

**Comment by cdelashmutt-pivotal** [comment]
Thanks for the contribution, ameet123!

**Pull request merged**
